export const newGameUrl = '/api/game/new/';
export const enterGameUrl = '/api/game/enter/';
export const attackUrl = '/api/attack/';
export const emptyShipTypeUrl = '/api/ship/';
export const invalidPlaceShipUrl = '/api/ship/shipType/';
export const placeBattleshipUrl = '/api/ship/battleship/';
export const getStatusUrl = '/api/game/status/';

// token not generated by server
export const fakeToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lX2lkIjoiNjAyOGZhNjJkMjNhYzIxYjBjMDg0MGEzIiwiaWQiOiI0NGY5YzdmZC0wZmI5LTRjYmEtOGIyNS00MWI0NzE5ODBlNTYiLCJyb2xlIjoiREVGRU5ERVIiLCJpYXQiOjE2MTMyOTgyNzQ3ODAsImV4cCI6MTYxMzI5ODI3ODM4MH0.6qzjuNdMX_L-IEdx74jmp0bh3BI6IfIvHMM-fHAOGfk';

// game id and token of defender from unexisting game generated by server
export const fakeValidId = '60292975702a682635bb44aa';
export const fakeValidToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lX2lkIjoiNjAyOTI5NzU3MDJhNjgyNjM1YmI0NGFhIiwiaWQiOiJhOTBmMWVmNS04MTIwLTQxZjktOWExMS04YjEzMGMwNTcxZTQiLCJyb2xlIjoiREVGRU5ERVIiLCJpYXQiOjE2MTMzMTAzMjU1NzEsImV4cCI6MTYxMzMxMDMyOTE3MX0.XleatO_ukx6iO79miYLGYjbtCmrFe7VdP4j-1ovoK0E';

// sample invalid request bodies to place ship
export const invalidBody = {
  type: 'abcd',
  start_x: 11.0,
  end_x: -99,
  start_y: -1.12,
  is_verticle: 'true',
};

export const coordAsArray = {
  type: 'abcd',
  start_x: [10, 2],
  start_y: [3, 9, 7],
  is_verticle: true,
};

// a valid request bodies to place ship
export const validBody = {
  type: 'cruiser', // should be ignored
  start_x: 5.0,
  end_x: -99, // should be ignored
  start_y: 4.0,
  is_verticle: true,
};

// extra data
export const validBodyExtra = {
  type: 'cruiser',
  start_x: 7,
  start_y: 4,
  is_verticle: false,
};
